const API_URL = 'http://netrunnerdb.com/api';
const CARD_TYPES = [
	'identity',
	'event',
	'hardware',
	'program',
	'resource',
	'agenda',
	'asset',
	'operation',
	'ice',
	'upgrade'
];
const CARD_SUBTYPES = [
	'g-mod',
	'run',
	'chip',
	'console',
	'icebreaker - fracter',
	'virus',
	'daemon',
	'icebreaker - killer',
	'icebreaker - ai',
	'icebreaker - decoder',
	'virtual',
	'location - seedy',
	'cyborg',
	'run - sabotage',
	'job',
	'location',
	'connection - seedy',
	'connection',
	'natural',
	'mod',
	'link',
	'location - connection',
	'remote',
	'icebreaker - ai - virus',
	'megacorp',
	'research',
	'advertisement',
	'ambush',
	'barrier - bioroid - ap',
	'sentry - bioroid - tracer - destroyer',
	'code gate - bioroid - ap',
	'sentry - destroyer',
	'initiative',
	'ambush - research',
	'gray ops',
	'code gate - deflector',
	'code gate',
	'trap - ap',
	'sentry - ap',
	'barrier - ap',
	'sysop - unorthodox',
	'ambush - facility',
	'sentry - tracer - observer',
	'region',
	'expansion',
	'security',
	'transaction',
	'black ops',
	'barrier',
	'sentry - tracer',
	'division',
	'bioroid',
	'executive',
	'condition',
	'trap',
	'sentry - bioroid - destroyer - tracer',
	'code gate - bioroid - tracer - ap',
	'sentry - bioroid - ap',
	'hostile',
	'gear',
	'stealth'
]

export {API_URL, CARD_TYPES};
